test_data={'image_jfif_file': WindowsPath('testdata/files/image.jfif')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
os_info=Windows, 10
python_version=3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]